### ISSUE TITLE
[documentation] Explain running with flux in more detail

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/executorlib#375]
Add a short explanation that `flux start` has to be called before users are able to use `Flux` with `executorlib`. Alternatively, use the custom jupyter kernel https://github.com/pyiron/executorlib/blob/main/binder/kernel.json

**Comment by samwaseda** [comment]
I've given it a try but I got the following error message `[Errno 2] No such file or directory: 'flux'`.

Steps I made:

1. Create a directory by: `mkdir -p ~/.local/share/jupyter/kernels/flux`
2. Insert the content of `kerne.json` into `~/.local/share/jupyter/kernels/flux/kernel.json`
3. Replace `/srv/conda/envs/notebook/bin/python` by the content of `which python`
4. Restart Jupyter server
5. Choose `Flux` from the top right of the notebook

**Comment by jan-janssen** [comment]
Do you have `flux-core` installed from conda?

**Comment by samwaseda** [comment]
Yes yes (otherwise it would be super awkward XD)

**Comment by jan-janssen** [comment]
Is flux installed in a specific conda environment e.g. a different one than your jupyter lab server? In that case you might need the absolute path to the `flux` executable in the `kernel.json` file.

**Comment by samwaseda** [comment]
ah true... ok it was almost as awkward as not installing `flux-core` but at least my problem got resolved. Thanks!

**Comment by jan-janssen** [comment]
The coupling of flux with jupyter is now covered in the installation section of the updated documentation https://executorlib.readthedocs.io/en/latest/installation.html#flux-with-jupyter
