### ISSUE TITLE
[documentation] Example usage help needed

### ISSUE THREAD

**Issue by srmnitc** [pyiron/executorlib#381]
Thanks for this nice package

I want to run a command line tool with the following run command `mpiexec -n 4 tool_name inputfile` from a jupyter notebook on my workstation. Is executorlib the right tool for this? If so, would it be possible to give a small example on how this can be run?

Thanks!

**Comment by jan-janssen** [comment]
`executorlib` is primarily designed to execute python functions, not so much external executables. Still you can do something like:
```python
import subprocess
from executorlib import Executor


def run_external():
    return subprocess.check_output("mpiexec -n 4 tool_name inputfile")


with Executor(max_cores=4, backend="local") as exe:
    future = exe.submit(run_external, resource_dict={"threads": 4})
    print(future.result())
```
Here we use `threads` because we only want one python process to start 4 sub processes using mpi4py inside the subprocess.

**Comment by jan-janssen** [comment]
I added a separate section in the updated documentation to discuss the interface to external executables: 
https://executorlib.readthedocs.io/en/latest/4-developer.html#external-executables
