### ISSUE TITLE
Can the process surving a disruption to the executor?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/executorlib#412]
I can successfully use `Executor` to submit python functions to a SLURM queue, but killing my executor instance has the unexpected (to me) effect of cancelling my slurm job.

E.g. I have the following code in `dev.py` in my pythonpath:

```python
def file_test(n):
    s = f"I got the number {n}"
    from time import sleep
    sleep(n)
    with open("file_test.txt", "w") as f:
        f.write(s)
    return s
```

If I then go into my notebook and execute

```python
from executorlib import Executor
from dev import file_test

with Executor(
    max_cores=1, 
    backend="slurm", 
    command_line_argument_lst=[
        "-n 1",
        "-N 1",
        "--account=...",
        "--partition=...",
        "--time=00:00:20",
    ]
) as exe:
    fs = exe.submit(file_test, 10)
    print(fs.result())
```

It works fine, I can see the slurm job start in `squeue`, it writes the file, and the future result prints what I expect.

What I'd like to be able to do is then shut down that notebook python process. This will lose the reference to the future, but I'm fine with that, I just want the function to still run and write the python process. Currently, I can see the job appear in `squeue` and then kill the notebook, and `executorlib` seems to be sending a shutdown signal to slurm when the executor dies and I see the warning below and no file ever gets written:

```
srun: interrupt (one more within 1 sec to abort)
srun: StepId=9252826.0 task 0: running
```

I looked at the kwargs and through the docs examples but don't see this mentioned -- is it possible to have the slurm job persist beyond the python process of the `Executor`?

**Comment by jan-janssen** [comment]
This is intentional, the executor is designed to kill all processes when it is shutdown, this applies to regular python processes and job steps inside a SLURM allocation. For submitting tasks independent of the executor use the cache based interface https://github.com/pyiron-dev/remote-executor

**Comment by liamhuber** [comment]
Ok, thanks for the quick reply.
